CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" varchar(100),
  "email" varchar(100) UNIQUE,
  "phone" varchar(20),
  "password" varchar(255),
  "role_id" bigint,
  "status" varchar(20),
  "created_at" datetime,
  "updated_at" datetime
);

CREATE TABLE "roles" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(50) UNIQUE
);

CREATE TABLE "permissions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(100) UNIQUE,
  "name" varchar(100)
);

CREATE TABLE "role_permissions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "role_id" bigint,
  "permission_id" bigint
);

CREATE TABLE "stores" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100),
  "address" varchar(255),
  "phone" varchar(20),
  "status" varchar(20),
  "created_at" datetime,
  "updated_at" datetime
);

CREATE TABLE "staff_stores" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "staff_id" bigint,
  "store_id" bigint,
  "position" varchar(50),
  "status" varchar(20),
  "created_at" datetime
);

CREATE TABLE "customer_addresses" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "receiver_name" varchar(100),
  "receiver_phone" varchar(20),
  "address" varchar(255),
  "is_default" boolean,
  "created_at" datetime,
  "updated_at" datetime
);

CREATE TABLE "categories" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100),
  "description" text,
  "status" varchar(20),
  "created_at" datetime,
  "updated_at" datetime
);

CREATE TABLE "products" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id" bigint,
  "name" varchar(100),
  "description" text,
  "image_url" varchar(255),
  "status" varchar(20),
  "created_at" datetime,
  "updated_at" datetime
);

CREATE TABLE "product_variants" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" bigint,
  "size" varchar(20),
  "price" decimal(12,2),
  "status" varchar(20)
);

CREATE TABLE "toppings" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100),
  "price" decimal(12,2),
  "status" varchar(20)
);

CREATE TABLE "product_toppings" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_id" bigint,
  "topping_id" bigint
);

CREATE TABLE "carts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "created_at" datetime,
  "updated_at" datetime
);

CREATE TABLE "cart_items" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cart_id" bigint,
  "product_variant_id" bigint,
  "quantity" int,
  "note" varchar(255)
);

CREATE TABLE "cart_item_toppings" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cart_item_id" bigint,
  "topping_id" bigint,
  "quantity" int
);

CREATE TABLE "orders" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "store_id" bigint,
  "address_id" bigint,
  "order_code" varchar(50) UNIQUE,
  "order_type" varchar(20),
  "status" varchar(30),
  "receiver_name" varchar(100),
  "receiver_phone" varchar(20),
  "delivery_address" varchar(255),
  "subtotal" decimal(12,2),
  "discount_amount" decimal(12,2),
  "total_amount" decimal(12,2),
  "note" varchar(255),
  "created_at" datetime,
  "updated_at" datetime
);

CREATE TABLE "order_items" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" bigint,
  "product_id" bigint,
  "product_variant_id" bigint,
  "product_name" varchar(100),
  "size" varchar(20),
  "unit_price" decimal(12,2),
  "quantity" int,
  "total_price" decimal(12,2),
  "note" varchar(255)
);

CREATE TABLE "order_item_toppings" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_item_id" bigint,
  "topping_id" bigint,
  "topping_name" varchar(100),
  "unit_price" decimal(12,2),
  "quantity" int,
  "total_price" decimal(12,2)
);

CREATE TABLE "payments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" bigint,
  "payment_method" varchar(30),
  "payment_status" varchar(30),
  "amount" decimal(12,2),
  "paid_at" datetime,
  "created_at" datetime
);

CREATE TABLE "promotions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE,
  "name" varchar(100),
  "discount_type" varchar(20),
  "discount_value" decimal(12,2),
  "min_order_amount" decimal(12,2),
  "start_date" datetime,
  "end_date" datetime,
  "usage_limit" int,
  "status" varchar(20)
);

CREATE TABLE "order_promotions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" bigint,
  "promotion_id" bigint,
  "discount_amount" decimal(12,2)
);

CREATE TABLE "ingredients" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar(50) UNIQUE,
  "name" varchar(100),
  "unit" varchar(20),
  "status" varchar(20),
  "created_at" datetime,
  "updated_at" datetime
);

CREATE TABLE "recipes" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "product_variant_id" bigint,
  "name" varchar(100),
  "status" varchar(20),
  "created_at" datetime,
  "updated_at" datetime
);

CREATE TABLE "recipe_ingredients" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "recipe_id" bigint,
  "ingredient_id" bigint,
  "quantity" decimal(12,2)
);

CREATE TABLE "topping_ingredients" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "topping_id" bigint,
  "ingredient_id" bigint,
  "quantity" decimal(12,2)
);

CREATE TABLE "store_ingredients" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "store_id" bigint,
  "ingredient_id" bigint,
  "quantity" decimal(12,2),
  "min_quantity" decimal(12,2),
  "updated_at" datetime
);

CREATE TABLE "goods_receipts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "store_id" bigint,
  "created_by" bigint,
  "receipt_code" varchar(50) UNIQUE,
  "total_amount" decimal(12,2),
  "note" varchar(255),
  "created_at" datetime
);

CREATE TABLE "goods_receipt_details" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "receipt_id" bigint,
  "ingredient_id" bigint,
  "quantity" decimal(12,2),
  "unit_price" decimal(12,2),
  "total_price" decimal(12,2)
);

CREATE TABLE "stock_movements" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "store_id" bigint,
  "ingredient_id" bigint,
  "movement_type" varchar(20),
  "quantity" decimal(12,2),
  "reference_type" varchar(30),
  "reference_id" bigint,
  "note" varchar(255),
  "created_at" datetime
);

ALTER TABLE "users" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "role_permissions" ADD FOREIGN KEY ("role_id") REFERENCES "roles" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "role_permissions" ADD FOREIGN KEY ("permission_id") REFERENCES "permissions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "staff_stores" ADD FOREIGN KEY ("staff_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "staff_stores" ADD FOREIGN KEY ("store_id") REFERENCES "stores" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "customer_addresses" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "products" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_variants" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_toppings" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "product_toppings" ADD FOREIGN KEY ("topping_id") REFERENCES "toppings" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "carts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cart_items" ADD FOREIGN KEY ("cart_id") REFERENCES "carts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cart_items" ADD FOREIGN KEY ("product_variant_id") REFERENCES "product_variants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cart_item_toppings" ADD FOREIGN KEY ("cart_item_id") REFERENCES "cart_items" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cart_item_toppings" ADD FOREIGN KEY ("topping_id") REFERENCES "toppings" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("store_id") REFERENCES "stores" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("address_id") REFERENCES "customer_addresses" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("product_id") REFERENCES "products" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("product_variant_id") REFERENCES "product_variants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_item_toppings" ADD FOREIGN KEY ("order_item_id") REFERENCES "order_items" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_item_toppings" ADD FOREIGN KEY ("topping_id") REFERENCES "toppings" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payments" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_promotions" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_promotions" ADD FOREIGN KEY ("promotion_id") REFERENCES "promotions" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "recipes" ADD FOREIGN KEY ("product_variant_id") REFERENCES "product_variants" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "recipe_ingredients" ADD FOREIGN KEY ("recipe_id") REFERENCES "recipes" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "recipe_ingredients" ADD FOREIGN KEY ("ingredient_id") REFERENCES "ingredients" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "topping_ingredients" ADD FOREIGN KEY ("topping_id") REFERENCES "toppings" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "topping_ingredients" ADD FOREIGN KEY ("ingredient_id") REFERENCES "ingredients" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "store_ingredients" ADD FOREIGN KEY ("store_id") REFERENCES "stores" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "store_ingredients" ADD FOREIGN KEY ("ingredient_id") REFERENCES "ingredients" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "goods_receipts" ADD FOREIGN KEY ("store_id") REFERENCES "stores" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "goods_receipts" ADD FOREIGN KEY ("created_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "goods_receipt_details" ADD FOREIGN KEY ("receipt_id") REFERENCES "goods_receipts" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "goods_receipt_details" ADD FOREIGN KEY ("ingredient_id") REFERENCES "ingredients" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "stock_movements" ADD FOREIGN KEY ("store_id") REFERENCES "stores" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "stock_movements" ADD FOREIGN KEY ("ingredient_id") REFERENCES "ingredients" ("id") DEFERRABLE INITIALLY IMMEDIATE;
