export const UI_TEXT = {
  common: {
    dashboard: "Bảng điều khiển",
    branches: "Quản lý chi nhánh",
    products: "Quản lý sản phẩm",
    categories: "Quản lý danh mục",
    employees: "Quản lý nhân viên",
    customers: "Quản lý khách hàng",
    orders: "Quản lý đơn hàng",
    promotions: "Quản lý khuyến mãi",
    analytics: "Báo cáo doanh thu",
    reports: "Báo cáo & Thống kê",
    settings: "Cài đặt hệ thống",
    inventory: "Quản lý kho hàng",
    revenue: "Doanh thu chi nhánh",
    pos: "Quầy bán hàng (POS)",
    history: "Lịch sử giao dịch",
    actions: "Thao tác",
    status: "Trạng thái",
    search: "Tìm kiếm...",
    filter: "Bộ lọc",
    all: "Tất cả",
    add: "Thêm mới",
    edit: "Chỉnh sửa",
    delete: "Xóa",
    save: "Lưu thông tin",
    cancel: "Hủy bỏ",
    confirm: "Xác nhận",
    loading: "Đang tải dữ liệu...",
    selectBranch: "Chọn chi nhánh",
    selectRole: "Chọn chức vụ",
    selectStatus: "Chọn trạng thái",
    selectCategory: "Chọn danh mục",
    date: "Ngày",
    price: "Đơn giá",
    quantity: "Số lượng",
    total: "Tổng cộng",
    description: "Mô tả",
    image: "Hình ảnh",
    active: "Hoạt động",
    inactive: "Ngừng hoạt động",
    logout: "Đăng xuất",
  },
  admin: {
    dashboardTitle: "Trụ sở chính - Tổng quan Hệ thống",
    revenueTitle: "Tổng doanh thu",
    ordersTitle: "Tổng đơn hàng",
    customersTitle: "Tổng khách hàng",
    branchesTitle: "Tổng chi nhánh",
    revenueMonthChart: "Doanh thu theo tháng",
    revenueBranchChart: "Doanh thu theo chi nhánh",
    bestSellersChart: "Sản phẩm bán chạy nhất",
    customerGrowthChart: "Tăng trưởng khách hàng",
    createBranch: "Tạo chi nhánh mới",
    editBranch: "Cập nhật chi nhánh",
    deleteBranchConfirm: "Bạn có chắc chắn muốn xóa chi nhánh này? Thao tác này không thể hoàn tác.",
    createProduct: "Thêm sản phẩm mới",
    editProduct: "Cập nhật sản phẩm",
    deleteProductConfirm: "Bạn có chắc chắn muốn xóa sản phẩm này?",
    createCategory: "Thêm danh mục mới",
    editCategory: "Cập nhật danh mục",
    deleteCategoryConfirm: "Bạn có chắc chắn muốn xóa danh mục này?",
    createEmployee: "Tuyển dụng nhân viên mới",
    editEmployee: "Cập nhật thông tin nhân viên",
    deleteEmployeeConfirm: "Bạn có chắc chắn muốn cho nhân viên này thôi việc?",
    createPromotion: "Tạo chương trình khuyến mãi",
    editPromotion: "Cập nhật chương trình khuyến mãi",
    deletePromotionConfirm: "Bạn có chắc chắn muốn xóa mã khuyến mãi này?",
  },
  manager: {
    dashboardTitle: "Cửa hàng trưởng - Báo cáo Chi nhánh",
    todayRevenue: "Doanh thu hôm nay",
    todayOrders: "Đơn hàng hôm nay",
    activeStaff: "Nhân viên đang trực",
    inventoryWarning: "Nguyên liệu sắp hết",
    orderWorkflow: "Quy trình xử lý đơn hàng",
    ingredientList: "Danh sách nguyên liệu",
    importStock: "Nhập thêm nguyên liệu",
    importStockTitle: "Phiếu nhập kho nguyên liệu",
    staffPerformance: "Hiệu suất nhân viên",
    workingShift: "Ca làm việc",
    weeklyRevenue: "Doanh thu tuần này",
    monthlyRevenue: "Doanh thu tháng này",
  },
  pos: {
    coffee: "Cà phê",
    tea: "Trà trái cây",
    cake: "Bánh ngọt",
    food: "Đồ ăn nhanh",
    cartTitle: "Đơn hàng hiện tại",
    emptyCart: "Chưa có món nào được chọn",
    addNote: "Thêm ghi chú...",
    payCash: "Tiền mặt",
    payCard: "Quẹt thẻ",
    payQR: "Quét mã QR",
    checkoutSuccess: "Thanh toán thành công!",
    orderCode: "Mã hóa đơn",
    receiptPreview: "Xem trước hóa đơn bán lẻ",
    printReceipt: "In hóa đơn",
    close: "Đóng cửa sổ",
    customerName: "Khách hàng",
    staffName: "Thu ngân",
    dateTime: "Thời gian",
    cashReceived: "Tiền khách đưa",
    cashReturned: "Tiền thối lại",
  },
  account: {
    title: "Cài đặt tài khoản",
    profileInfo: "Thông tin cá nhân",
    security: "Bảo mật & Mật khẩu",
    preferences: "Cấu hình ứng dụng",
    permissions: "Quyền hạn tài khoản",
    fullName: "Họ và tên",
    email: "Địa chỉ Email",
    phone: "Số điện thoại",
    role: "Vai trò hiện tại",
    joinedDate: "Ngày tham gia",
    editProfile: "Chỉnh sửa thông tin",
    changePassword: "Đổi mật khẩu",
    currentPassword: "Mật khẩu hiện tại",
    newPassword: "Mật khẩu mới",
    confirmNewPassword: "Xác nhận mật khẩu mới",
    twoFactor: "Xác thực 2 yếu tố (2FA)",
    language: "Ngôn ngữ hiển thị",
    darkMode: "Chế độ tối (Dark Mode)",
    notifyOrders: "Nhận thông báo đơn hàng",
    notifyMarketing: "Nhận email marketing",
    logout: "Đăng xuất tài khoản",
    saveSuccess: "Cập nhật thông tin tài khoản thành công!",
    logoutConfirm: "Bạn có chắc chắn muốn đăng xuất?",
    passwordError: "Xác nhận mật khẩu không khớp!",
  }
};
