package com.lowlands.coffee.modules.report.export;

import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

public class ExcelSheetWriter<T> {

    private final Workbook workbook;
    private final Sheet sheet;
    private final ExcelStyleHelper styles;

    public ExcelSheetWriter(Workbook workbook, Sheet sheet, ExcelStyleHelper styles) {
        this.workbook = workbook;
        this.sheet = sheet;
        this.styles = styles;
    }

    public void write(ReportExportMetadata metadata, List<ExcelColumnDefinition<T>> columns, List<T> rows) {
        int rowIndex = 0;
        Row titleRow = sheet.createRow(rowIndex++);
        Cell titleCell = titleRow.createCell(0);
        titleCell.setCellValue(metadata.reportName());
        titleCell.setCellStyle(styles.title());

        rowIndex = writeMetadata(rowIndex, "Generated Time", metadata.generatedAt().toString());
        rowIndex = writeMetadata(rowIndex, "Generated By", metadata.generatedBy());
        rowIndex = writeMetadata(rowIndex, "Date Range", metadata.fromDate() + " to " + metadata.toDate());
        rowIndex = writeMetadata(rowIndex, "Store", metadata.store());
        rowIndex = writeMetadata(rowIndex, "Filter Summary", metadata.filterSummary());
        rowIndex++;

        int headerRowIndex = rowIndex;
        Row headerRow = sheet.createRow(rowIndex++);
        for (int i = 0; i < columns.size(); i++) {
            Cell cell = headerRow.createCell(i);
            cell.setCellValue(columns.get(i).header());
            cell.setCellStyle(styles.headerStyle());
        }

        for (T dataRow : rows) {
            Row sheetRow = sheet.createRow(rowIndex++);
            for (int i = 0; i < columns.size(); i++) {
                ExcelColumnDefinition<T> column = columns.get(i);
                Cell cell = sheetRow.createCell(i);
                writeCell(cell, column.type(), column.valueExtractor().apply(dataRow));
            }
        }

        sheet.createFreezePane(0, headerRowIndex + 1);
        for (int i = 0; i < columns.size(); i++) {
            sheet.autoSizeColumn(i);
            int width = sheet.getColumnWidth(i);
            sheet.setColumnWidth(i, Math.min(Math.max(width + 512, 3000), 12000));
        }
    }

    private int writeMetadata(int rowIndex, String label, String value) {
        Row row = sheet.createRow(rowIndex);
        Cell labelCell = row.createCell(0);
        labelCell.setCellValue(label);
        labelCell.setCellStyle(styles.label());

        Cell valueCell = row.createCell(1);
        valueCell.setCellValue(value == null ? "" : value);
        valueCell.setCellStyle(styles.value());
        return rowIndex + 1;
    }

    private void writeCell(Cell cell, ExcelValueType type, Object value) {
        if (value == null) {
            cell.setBlank();
            cell.setCellStyle(styles.text());
            return;
        }
        switch (type) {
            case NUMBER -> {
                cell.setCellValue(toDouble(value));
                cell.setCellStyle(styles.number());
            }
            case CURRENCY -> {
                cell.setCellValue(toDouble(value));
                cell.setCellStyle(styles.currency());
            }
            case DATE -> {
                if (value instanceof LocalDate localDate) {
                    cell.setCellValue(localDate);
                    cell.setCellStyle(styles.date());
                } else {
                    cell.setCellValue(value.toString());
                    cell.setCellStyle(styles.text());
                }
            }
            case DATETIME -> {
                if (value instanceof LocalDateTime localDateTime) {
                    cell.setCellValue(localDateTime);
                    cell.setCellStyle(styles.dateTime());
                } else {
                    cell.setCellValue(value.toString());
                    cell.setCellStyle(styles.text());
                }
            }
            case TEXT -> {
                cell.setCellValue(value.toString());
                cell.setCellStyle(styles.text());
            }
        }
    }

    private double toDouble(Object value) {
        if (value instanceof BigDecimal decimal) {
            return decimal.doubleValue();
        }
        if (value instanceof Number number) {
            return number.doubleValue();
        }
        return Double.parseDouble(value.toString());
    }
}
